### ISSUE TITLE
外部容器resize后，echart无法自适应

### ISSUE THREAD

**Issue by aspiders** [bornkiller/echarts-ng#3]
怎样实现外部容器resize后，echart自适应？echarts-ng.js里面有如instance.resize()，应该是实现重画图的，怎样在外部controller使用？请指点，谢谢！
@bornkiller

**Comment by bornkiller** [comment]
这个目前正在考虑封装内部实现，暂时可以通过获取实例，直接调用`resize`的方法解决。

**Comment by bornkiller** [comment]
元旦结束新版本迭代。
