### ISSUE TITLE
能否支持下angularjs2的版本，谢谢

### ISSUE THREAD

**Issue by c429013730** [bornkiller/echarts-ng#4]
你知道有angularjs2和echarts3的库吗？

**Comment by bornkiller** [comment]
`Angular2`应该可以在`directive`, `component`层级直接调用`echarts`，我觉得没有必要再做一层封装。

**Comment by ntfs32** [comment]
能给个范例这么使用么？，没找到相关的 直接 `import * as echarts from 'echarts';`
会有问题 会找不到 module
`error TS2307: Cannot find module 'echarts'.`

**Comment by bornkiller** [comment]
元旦结束会有较大更新，可以更好地支持迁移，解决此问题 @c429013730 @ntfs32
