### ISSUE TITLE
Change theme and import new ones

### ISSUE THREAD

**Issue by sbokorna** [bornkiller/echarts-ng#5]
Hello,

I would like to change the theme with one from the original echarts site (the blue one).

How can I do it?

Thanks

**Comment by bornkiller** [comment]
I suppose you already import the theme script, then try the code below.
I hope it helpful.

```js
angular.module('application').config(function($echartsProvider) {
  $echartsProvider.setGlobalOption({
    theme: 'theme name here'
  });
});
```

**Comment by sbokorna** [comment]
Thanks, this is the good way!
